server:
  port: 9999

test:
  uri: http://httpbin.org:80

# http://www.ityouknow.com/springcloud/2018/12/12/spring-cloud-gateway-start.html
#spring:
#  cloud:
#    gateway:
#      loadbalancer:
#        use404: true
#      routes:
#        - id: neo_route
#          uri: http://www.ityouknow.com
#          predicates:
#            - Path=/spring-cloud
##        - id: time_route
##          uri: http://www.ityouknow.com
##          predicates:
##            - After=2018-01-20T06:06:06+08:00[Asia/Shanghai]
#        - id: header_route
#          uri: http://ityouknow.com
#          predicates:
#            - Header=X-Request-Id, \d+
#
#        - id: lb_route
#          uri: lb://customRibbon
#          predicates:
#            - After=2018-01-20T06:06:06+08:00[Asia/Shanghai]

# 静态lb必须要关闭eureka的服务注册与发现
#ribbon:
#  eureka:
#    enabled: false
#
#customRibbon:
#  ribbon:
#    # 随机规则
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#    listOfServers: http://ityouknow.com
logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway: INFO


# Master slave:
# https://github.com/apache/incubator-shardingsphere-example/blob/dev/sharding-jdbc-example/sharding-example/sharding-spring-boot-jpa-example/src/main/resources/application-master-slave.properties
# https://github.com/apache/incubator-shardingsphere-example/blob/dev/sharding-jdbc-example/sharding-example/sharding-spring-boot-jpa-example/src/main/resources/application-sharding-master-slave.properties
spring:
  shardingsphere:
    datasource:
      names: master,slave0,slave1
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/master?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
        username: root
        password: 123456
      slave0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/slave0?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
        username: root
        password: 123456
      slave1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/slave1?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
        username: root
        password: 123456

    masterslave:
      name: ms
      master-data-source-name: master
      slave-data-source-names: slave0,slave1
      load-balance-algorithm-type: round_robin

    props:
      sql:
        show: true
#  jpa:
#    database: MYSQL
#    database-platform: org.hibernate.dialect.MySQLDialect
#    show-sql: false
#    properties:
#      hibernate:
#        current_context_class: org.springframework.orm.hibernate.SpringSessionContext
